name: test3

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  delete_data:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: .\build.bat
      - shell: cmd
